export const STRINGS = {
  common: {
    saveAndExit: "Save & Exit",
    continue: "Continue",
    cancel: "Cancel",
    done: "Done",
    play: "Play",
    stop: "Stop",
    delete: "Delete",
    back: "Back",
  },
  write: {
    placeholder: "Take a minute to breathe and write…",
    recording: "Recording...",
    tapToRecord: "Tap to Record",
    addPhoto: "Add Photo",
    photoPrompt: "Capture a moment or choose from your gallery.",
    chooseLibrary: "Choose from Library",
    takePhoto: "Take Photo",
    permissionDenied: "Permission Denied",
    micPermissionMsg: "Allow microphone access to record voice notes.",
    camPermissionMsg: "Camera access is needed to take photos.",
    emptyAlert: "Empty Entry",
    emptyMsg: "Please write something or record audio first.",
    toastGratitude: "+10 XP Gratitude Bonus!",
  },
  timer: {
    writing: "🖊️ Writing",
    break: "⏸️ Break",
    paused: "Paused",
    skipBreak: "Skip Break",
    show: "Show Timer",
    hide: "Hide Timer",
  }
};