import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { JournalEntry } from '../stores/entriesStore';

type ExportFormat = 'txt' | 'pdf' | 'json' | 'csv';

export const exportSingleEntry = async (entry: JournalEntry, format: ExportFormat = 'txt') => {
  try {
    let fileUri = '';
    let mimeType = '';
    let fileName = `MindfulMinute_${entry.date}`;

if (format === 'pdf') {
      fileName += '.pdf';
      mimeType = 'application/pdf';
      
      const htmlContent = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <style>
              @import url('https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;1,300&display=swap');
              body { 
                font-family: 'Merriweather', Georgia, serif; 
                padding: 40px; 
                color: #1F2937; 
                background-color: #FDFBF7;
                line-height: 1.6;
              }
              h1 { 
                color: #3730A3; 
                text-align: center; 
                font-weight: 300; 
                letter-spacing: 2px; 
                text-transform: uppercase; 
                font-size: 24px;
                margin-bottom: 24px; 
                border-bottom: 1px solid #E5E7EB;
                padding-bottom: 20px;
              }
              .meta { 
                display: flex; 
                justify-content: space-between; 
                margin-bottom: 30px; 
                font-family: Helvetica, sans-serif;
                font-size: 12px;
                color: #6B7280;
                text-transform: uppercase;
                letter-spacing: 1px;
              }
              .prompt-box { 
                background-color: #F3F4F6; 
                padding: 20px; 
                border-left: 4px solid #3730A3; 
                border-radius: 4px; 
                margin-bottom: 30px; 
                font-style: italic;
                color: #4B5563;
              }
              .content { 
                font-size: 16px; 
                color: #111827; 
                white-space: pre-wrap; 
                margin-bottom: 40px; 
              }
              .footer { 
                text-align: center; 
                font-size: 10px; 
                color: #9CA3AF; 
                font-family: Helvetica, sans-serif; 
                margin-top: 40px; 
                border-top: 1px solid #E5E7EB; 
                padding-top: 20px; 
              }
            </style>
          </head>
          <body>
            <h1>Micro Muse</h1>
            <div class="meta">
              <span>${new Date(entry.date).toLocaleDateString()}</span>
              <span>${entry.moodTag?.value || 'Untracked'}</span>
            </div>
            <div class="prompt-box">
              ${entry.prompt?.text || entry.promptText || "Freestyle Entry"}
            </div>
            <div class="content">${entry.text}</div>
            <div class="footer">Generated by Micro Muse</div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      fileUri = uri;

    } else if (format === 'json') {
      fileName += '.json';
      mimeType = 'application/json';
      const jsonContent = JSON.stringify(entry, null, 2);
      fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, jsonContent);

    } else if (format === 'csv') {
      fileName += '.csv';
      mimeType = 'text/csv';
      const cleanText = (entry.text || '').replace(/"/g, '""'); 
      const cleanPrompt = (entry.prompt?.text || '').replace(/"/g, '""');
      const csvContent = `Date,Prompt,Mood,Text\n"${entry.date}","${cleanPrompt}","${entry.moodTag?.value || ''}","${cleanText}"`;
      fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, csvContent);

    } else {
      // Default TXT
      fileName += '.txt';
      mimeType = 'text/plain';
      const textContent = `Date: ${entry.date}\nPrompt: ${entry.prompt?.text || 'None'}\nMood: ${entry.moodTag?.value || 'None'}\n\n${entry.text}`;
      fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, textContent);
    }

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(fileUri, {
        mimeType: mimeType,
        dialogTitle: `Export Entry as ${format.toUpperCase()}`,
        UTI: mimeType 
      });
    } else {
      alert("Sharing is not available on this device");
    }

  } catch (error) {
    console.error("Export failed:", error);
    alert("Failed to export file.");
  }
};
export const exportBulkEntries = async (entries: JournalEntry[], format: ExportFormat = 'json') => {
  try {
    let fileUri = '';
    let mimeType = '';
    const timestamp = new Date().toISOString().split('T')[0];
    let fileName = `MindfulMinute_Full_Export_${timestamp}`;

    if (format === 'pdf') {
      fileName += '.pdf';
      mimeType = 'application/pdf';
      
      let htmlContent = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <style>
              body { font-family: Helvetica, sans-serif; padding: 40px; color: #1F2937; }
              h1 { color: #6366F1; text-align: center; margin-bottom: 10px; }
              .subtitle { text-align: center; color: #6B7280; margin-bottom: 40px; font-size: 12px; }
              .entry { margin-bottom: 30px; page-break-inside: avoid; border: 1px solid #E5E7EB; border-radius: 8px; padding: 20px; }
              .header { display: flex; justify-content: space-between; border-bottom: 1px solid #F3F4F6; padding-bottom: 10px; margin-bottom: 15px; }
              .date { color: #6366F1; font-weight: bold; font-size: 16px; }
              .mood { background-color: #EEF2FF; color: #6366F1; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
              .prompt { font-weight: 600; color: #374151; margin-bottom: 8px; font-size: 14px; }
              .text { font-size: 14px; line-height: 1.6; white-space: pre-wrap; color: #4B5563; }
              .footer { text-align: center; font-size: 10px; color: #9CA3AF; margin-top: 40px; }
            </style>
          </head>
          <body>
            <h1>Micro Muse Journal</h1>
            <div class="subtitle">Exported on ${new Date().toLocaleDateString()} • ${entries.length} Entries</div>
      `;

      entries.forEach(entry => {
        htmlContent += `
          <div class="entry">
            <div class="header">
              <span class="date">${new Date(entry.date).toLocaleDateString()}</span>
              ${entry.moodTag?.value ? `<span class="mood">${entry.moodTag.value}</span>` : ''}
            </div>
            <div class="prompt">${entry.prompt?.text || entry.promptText || 'Freestyle'}</div>
            <div class="text">${entry.text || ''}</div>
            ${entry.imageUri ? `<div style="margin-top:10px; font-size:10px; color:#999;">[Attached Image]</div>` : ''}
          </div>
        `;
      });

      htmlContent += `
            <div class="footer">Generated by Micro Muse</div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      fileUri = uri;

    } else if (format === 'csv') {
      fileName += '.csv';
      mimeType = 'text/csv';
      let csvContent = 'Date,Time,Mood,Prompt,Text\n';
      
      entries.forEach(entry => {
        const date = entry.date;
        const time = entry.createdAt ? new Date(entry.createdAt).toLocaleTimeString() : '';
        const mood = (entry.moodTag?.value || '').replace(/"/g, '""');
        const prompt = (entry.prompt?.text || entry.promptText || '').replace(/"/g, '""');
        const text = (entry.text || '').replace(/"/g, '""');
        
        csvContent += `"${date}","${time}","${mood}","${prompt}","${text}"\n`;
      });
      
      fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, csvContent);

    } else {
      // JSON (Default for Backup)
      fileName += '.json';
      mimeType = 'application/json';
      const jsonContent = JSON.stringify(entries, null, 2);
      fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, jsonContent);
    }

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(fileUri, {
        mimeType: mimeType,
        dialogTitle: `Download All Data (${format.toUpperCase()})`,
        UTI: mimeType 
      });
    } else {
      alert("Sharing is not available");
    }

  } catch (error) {
    console.error("Bulk export failed:", error);
    alert("Failed to export data.");
  }
};

export const exportSharedJournalPDF = async (journalName: string, entries: any[]) => {
  try {
    // Sort chronological
    const sorted = [...entries].sort((a, b) => (a.createdAt || 0) - (b.createdAt || 0));
    
    let htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1F2937; background-color: #fff; }
            h1 { color: #3730A3; text-align: center; border-bottom: 2px solid #E5E7EB; padding-bottom: 20px; margin-bottom: 30px; }
            .meta { text-align: center; color: #6B7280; font-size: 12px; margin-bottom: 40px; }
            .entry { margin-bottom: 24px; padding: 16px; background-color: #F9FAFB; border-radius: 12px; border: 1px solid #F3F4F6; page-break-inside: avoid; }
            .entry-header { display: flex; justify-content: space-between; margin-bottom: 8px; border-bottom: 1px solid #E5E7EB; padding-bottom: 8px; }
            .author { font-weight: bold; color: #4F46E5; font-size: 14px; }
            .date { font-size: 12px; color: #9CA3AF; }
            .text { font-size: 15px; line-height: 1.6; color: #374151; white-space: pre-wrap; }
            .footer { text-align: center; font-size: 10px; color: #9CA3AF; margin-top: 50px; border-top: 1px solid #E5E7EB; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>${journalName}</h1>
          <div class="meta">
            Exported on ${new Date().toLocaleDateString()} • ${entries.length} Entries
          </div>
    `;

    sorted.forEach(entry => {
      const dateStr = entry.createdAt 
        ? new Date(entry.createdAt).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })
        : 'Unknown Date';

      htmlContent += `
        <div class="entry">
          <div class="entry-header">
            <span class="author">${entry.authorName || 'Anonymous'}</span>
            <span class="date">${dateStr}</span>
          </div>
          <div class="text">${entry.text}</div>
        </div>
      `;
    });

    htmlContent += `
          <div class="footer">Generated by Micro Muse</div>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, {
        UTI: '.pdf',
        mimeType: 'application/pdf',
        dialogTitle: `Export ${journalName}`
      });
    } else {
      alert("Sharing is not available");
    }

  } catch (error) {
    console.error("Export failed:", error);
    alert("Failed to create PDF.");
  }
};