import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { JournalEntry } from '../stores/entriesStore';

type ExportFormat = 'txt' | 'pdf' | 'json' | 'csv';

export const exportSingleEntry = async (entry: JournalEntry, format: ExportFormat = 'txt') => {
  try {
    let fileUri = '';
    let mimeType = '';
    let fileName = `MindfulMinute_${entry.date}`;

    if (format === 'pdf') {
      fileName += '.pdf';
      mimeType = 'application/pdf';
      
      const htmlContent = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <style>
              body { font-family: Helvetica, sans-serif; padding: 40px; color: #1F2937; }
              h1 { color: #6366F1; border-bottom: 2px solid #E5E7EB; padding-bottom: 16px; margin-bottom: 24px; }
              .meta { margin-bottom: 30px; color: #6B7280; font-size: 14px; }
              .label { font-weight: bold; color: #374151; margin-right: 8px; }
              .prompt-box { background-color: #F3F4F6; padding: 16px; border-left: 4px solid #6366F1; border-radius: 8px; margin-bottom: 24px; }
              .content { font-size: 16px; line-height: 1.6; white-space: pre-wrap; margin-bottom: 40px; }
              .footer { text-align: center; font-size: 10px; color: #9CA3AF; margin-top: 40px; border-top: 1px solid #F3F4F6; padding-top: 20px; }
            </style>
          </head>
          <body>
            <h1>Mindful Minute Entry</h1>
            <div class="meta">
              <p><span class="label">Date:</span> ${new Date(entry.date).toLocaleDateString()}</p>
              <p><span class="label">Mood:</span> ${entry.moodTag?.value || 'Not tracked'}</p>
            </div>
            <div class="prompt-box">
              <strong>Prompt:</strong> ${entry.prompt?.text || entry.promptText || "Freestyle Entry"}
            </div>
            <div class="content">${entry.text}</div>
            <div class="footer">Generated by Mindful Minute</div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      fileUri = uri;

    } else if (format === 'json') {
      fileName += '.json';
      mimeType = 'application/json';
      const jsonContent = JSON.stringify(entry, null, 2);
      fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, jsonContent);

    } else if (format === 'csv') {
      fileName += '.csv';
      mimeType = 'text/csv';
      const cleanText = (entry.text || '').replace(/"/g, '""'); 
      const cleanPrompt = (entry.prompt?.text || '').replace(/"/g, '""');
      const csvContent = `Date,Prompt,Mood,Text\n"${entry.date}","${cleanPrompt}","${entry.moodTag?.value || ''}","${cleanText}"`;
      fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, csvContent);

    } else {
      // Default TXT
      fileName += '.txt';
      mimeType = 'text/plain';
      const textContent = `Date: ${entry.date}\nPrompt: ${entry.prompt?.text || 'None'}\nMood: ${entry.moodTag?.value || 'None'}\n\n${entry.text}`;
      fileUri = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(fileUri, textContent);
    }

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(fileUri, {
        mimeType: mimeType,
        dialogTitle: `Export Entry as ${format.toUpperCase()}`,
        UTI: mimeType 
      });
    } else {
      alert("Sharing is not available on this device");
    }

  } catch (error) {
    console.error("Export failed:", error);
    alert("Failed to export file.");
  }
};